spring:
  application:
    name: portfolio_urless_backend
  datasource:
    #driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #password: Sa.Password
    #url: jdbc:sqlserver://127.0.0.1:1433;databaseName=urless;encrypt=true;trustServerCertificate=true;
    #username: sa
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_USERNAME}
    username: ${SPRING_DATASOURCE_USERNAME}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.steevenengracia: INFO