version: '3.8'

volumes:
  mssql-dev-data:

services:
  app-dev:
    container_name: app-dev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql-dev:1433;databaseName=urless;encrypt=true;trustServerCertificate=true;
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: Sa.Password
    
    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "8080:8080"  # Expose app port to host

    depends_on:
      mssql-dev:
        condition: service_healthy

    networks:
      - app-dev-network
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mssql-dev:
    container_name: mssql-dev
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    volumes:
      - mssql-dev-data:/var/opt/mssql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      MSSQL_SA_PASSWORD: Sa.Password
      ACCEPT_EULA      : Y
    
    ports:
      - "1433:1433"  # Expose SQL Server port to host

    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Sa.Password", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2g
          
    networks:
      - app-dev-network
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  app-dev-network:
    driver: bridge